language: node_js
node_js:
    - '8'
    - 'node'
    - 'lts/*'
before_install:
    - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
install: npm install
script:
    - 'npm run test'
after_script:
    - './node_modules/.bin/codecov --token=8068a1a5-0654-4095-8769-68a374efc7de'
